ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = petsccompat.c
SOURCEF  =
SOURCEH  =
OBJSC    = petsccompat.o
OBJSF    =
LIBBASE  = libpetscext_compat
MANSEC   = 
LOCDIR   = src/compat/

include ${PETSCEXT_DIR}/conf/petscext_common
