ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = petscext_vecimpls.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscext_vec
DIRS     = block
LOCDIR   = src/vec/impls/

include ${PETSCEXT2_DIR}/conf/petscext_common
