ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mat-schur-ops.c mat-schur.c
SOURCEF  =
SOURCEH  =
OBJSC    = mat-schur-ops.o mat-schur.o
OBJSF    =
LIBBASE  = libpetscext_mat
MANSEC   = Mat
LOCDIR   = src/mat/impls/schur/

include ${PETSCEXT_DIR}/conf/petscext_common
