ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = BlockSNESMFFD.c
SOURCEF  =
SOURCEH  =
OBJSC    = BlockSNESMFFD.o
OBJSF    =
LIBBASE  = libpetscext_mat
MANSEC   = Mat
LOCDIR   = src/mat/utils/

include ${PETSCEXT_DIR}/conf/petscext_common
