ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pcx_register.c
SOURCEF  =
SOURCEH  =
OBJSC    = pcx_register.o
OBJSF    =
LIBBASE  = libpetscext_pc
MANSEC   = PC
LOCDIR   = src/pc/register/

include ${PETSCEXT2_DIR}/conf/petscext_common
