ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = kspx_register.c
SOURCEF  =
SOURCEH  =
OBJSC    = kspx_register.o
OBJSF    =
LIBBASE  = libpetscext_ksp
MANSEC   = KSP
LOCDIR   = src/ksp/register/

include ${PETSCEXT2_DIR}/conf/petscext_common
