ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = petscext_kspimpls.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscext_ksp
DIRS     = cgr
LOCDIR   = src/ksp/impls/

include ${PETSCEXT_DIR}/conf/petscext_common
