ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vec-block-ops.c vec-block.c
SOURCEF  =
SOURCEH  =
OBJSC    = vec-block-ops.o vec-block.o
OBJSF    =
LIBBASE  = libpetscext_vec
MANSEC   = Vec
LOCDIR   = src/vec/impls/block/

include ${PETSCEXT2_DIR}/conf/petscext_common
