ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pc-block-ops.c pc-block.c
SOURCEF  =
SOURCEH  =
OBJSC    = pc-block-ops.o pc-block.o
OBJSF    =
LIBBASE  = libpetscext_pc
MANSEC   = PC
LOCDIR   = src/pc/impls/block/

include ${PETSCEXT2_DIR}/conf/petscext_common
