ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  =
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscext_snes
MANSEC   = SNES
LOCDIR   = src/snes/utils/

include ${PETSCEXT_DIR}/conf/petscext_common
