ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mat-symbolic_transpose.c mat-symbolic_transpose-ops.c
SOURCEF  =
SOURCEH  =
OBJSC    = mat-symbolic_transpose.o mat-symbolic_transpose-ops.o
OBJSF    =
LIBBASE  = libpetscext_mat
MANSEC   = Mat
LOCDIR   = src/mat/impls/symtrans/

include ${PETSCEXT_DIR}/conf/petscext_common
