ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mat_fill_stride.c mataij_identity_new.c mataij_new.c \
		KSPSetRelativeRhsConvergenceTest.c MatrixMarketIO.c MatNullSpaceQuery.c \
		MatFreeComputeExplicitOperator.c MatVecViewers.c nullspace.c  MatMPIAIJOps.c
SOURCEF  =
SOURCEH  =
OBJSC    = mat_fill_stride.o mataij_identity_new.o mataij_new.o \
		KSPSetRelativeRhsConvergenceTest.o MatrixMarketIO.o MatNullSpaceQuery.o \
		MatFreeComputeExplicitOperator.o MatVecViewers.o nullspace.o  MatMPIAIJOps.o
OBJSF    =
LIBBASE  = libpetscext_helpers
MANSEC   = 
LOCDIR   = src/helpers/

include ${PETSCEXT2_DIR}/conf/petscext_common
