ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = petscext_pcimpls.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscext_pc
DIRS     = block bschur
LOCDIR   = src/pc/impls/

include ${PETSCEXT_DIR}/conf/petscext_common
