ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = picard.c
SOURCEF  =
SOURCEH  =
OBJSC    = picard.o
OBJSF    =
LIBBASE  = libpetscext_snes
MANSEC   = SNES
LOCDIR   = src/snes/impls/picard/

include ${PETSCEXT2_DIR}/conf/petscext_common
