ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  =
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscext_pc
MANSEC   = PC
LOCDIR   = src/pc/utils/

include ${PETSCEXT_DIR}/conf/petscext_common
