CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = petscext.h petscext_snes.h petscext_vec.h petscextversion.h petscextblaslapack.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscext_vec
DIRS     = finclude
LOCDIR   = include/
MANSEC   = 

include ${PETSCEXT2_DIR}/conf/petscext_common

runexamples:



