ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = VecNormBlock.c KSPResidualNormBlock.c PetscExtInit.c
SOURCEF  =
SOURCEH  =
OBJSC    = VecNormBlock.o KSPResidualNormBlock.o PetscExtInit.o
OBJSF    =
LIBBASE  = libpetscext_utils
MANSEC   = 
LOCDIR   = src/utils/

include ${PETSCEXT_DIR}/conf/petscext_common
