ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = matx_register.c
SOURCEF  =
SOURCEH  =
OBJSC    = matx_register.o
OBJSF    =
LIBBASE  = libpetscext_mat
MANSEC   = Mat
LOCDIR   = src/mat/register/

include ${PETSCEXT_DIR}/conf/petscext_common
