ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pc-bschur-ops.c pc-bschur.c
SOURCEF  =
SOURCEH  =
OBJSC    = pc-bschur-ops.o pc-bschur.o
OBJSF    =
LIBBASE  = libpetscext_pc
MANSEC   = PC
LOCDIR   = src/pc/impls/bschur/

include ${PETSCEXT2_DIR}/conf/petscext_common
