ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mat-restrictscatter.c mat-restrictscatter-ops.c
SOURCEF  =
SOURCEH  =
OBJSC    = mat-restrictscatter.o mat-restrictscatter-ops.o
OBJSF    =
LIBBASE  = libpetscext_mat
MANSEC   = Mat
LOCDIR   = src/mat/impls/mat-restrictscatter/

include ${PETSCEXT_DIR}/conf/petscext_common
