ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  =
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscext_vec
MANSEC   = Vec
LOCDIR   = src/vec/utils/

include ${PETSCEXT_DIR}/conf/petscext_common
