ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = cgr.c
SOURCEF  =
SOURCEH  =
OBJSC    = cgr.o
OBJSF    =
LIBBASE  = libpetscext_ksp
MANSEC   = KSP
LOCDIR   = src/ksp/impls/cgr/

include ${PETSCEXT2_DIR}/conf/petscext_common
