ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = petscext_snesimpls.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscext_snes
DIRS     = picard
LOCDIR   = src/snes/impls/

include ${PETSCEXT_DIR}/conf/petscext_common
