ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =  
SOURCEF  =
SOURCEH  = petscext_matimpls.h
OBJSC    =
OBJSF    =
LIBBASE  = libpetscext_mat
DIRS     = block symtrans schur restrictscatter
LOCDIR   = src/mat/impls/

include ${PETSCEXT_DIR}/conf/petscext_common
