#ifndef __Solvers_Assembly_types_h__
#define __Solvers_Assembly_types_h__

typedef struct PressMassMatrixTerm PressMassMatrixTerm;
typedef struct VelocityMassMatrixTerm VelocityMassMatrixTerm;
typedef struct Matrix_NaiNbj Matrix_NaiNbj;
typedef struct ViscousPenaltyConstMatrixCartesian   ViscousPenaltyConstMatrixCartesian;

#endif

