ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = snesx_register.c
SOURCEF  =
SOURCEH  =
OBJSC    = snesx_register.o
OBJSF    =
LIBBASE  = libpetscext_snes
MANSEC   = SNES
LOCDIR   = src/snes/register/

include ${PETSCEXT2_DIR}/conf/petscext_common
