ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vecx_register.c
SOURCEF  =
SOURCEH  =
OBJSC    = vecx_register.o
OBJSF    =
LIBBASE  = libpetscext_vec
MANSEC   = Vec
LOCDIR   = src/vec/register/

include ${PETSCEXT_DIR}/conf/petscext_common
