ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  =
OBJSC    = 
OBJSF    =
LIBBASE  = libpetscext_ksp
MANSEC   = KSP
LOCDIR   = src/ksp/utils/

include ${PETSCEXT_DIR}/conf/petscext_common
