function setAll(a,b){for(var c=document.getElementsByClassName(b),d=0;d<c.length;d++)c[d].style.display=a}function localStorageDefault(a,b){return varDefault(localStorage[a],b)}getSourceFromElement=function(a){var b=document.getElementById(a);if(!b)return null;a="";for(b=b.firstChild;b;)3==b.nodeType&&(a+=b.textContent),b=b.nextSibling;return a};function varDefault(a,b){return a?a:b}function removeChildren(a){if(a.hasChildNodes())for(;0<a.childNodes.length;)a.removeChild(a.firstChild)}
window.requestAnimationFrame||(window.requestAnimationFrame=function(){return window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame}());function requestFullScreen(a){a=document.getElementById(a);a.requestFullscreen?a.requestFullscreen():a.mozRequestFullScreen?a.mozRequestFullScreen():a.webkitRequestFullScreen&&a.webkitRequestFullScreen()}function $(a,b){return("object"==typeof b?b:document).getElementById(a)}
function $S(a){if(a=$(a))return a.style}function toggle(a){var b=$S(a).display;"none"==b||!b?$S(a).display="block":$S(a).display="none"}function typeOf(a){var b=typeof a;"object"===b&&(a?"number"===typeof a.length&&!a.propertyIsEnumerable("length")&&"function"===typeof a.splice&&(b="array"):b="null");return b}function isEmpty(a){var b,c;if("object"===typeOf(a))for(b in a)if(c=a[b],void 0!==c&&"function"!==typeOf(c))return!1;return!0}
String.prototype.hashCode||(String.prototype.hashCode=function(){var a=0;if(0==this.length)return a;for(i=0;i<this.length;i++)chr=this.charCodeAt(i),a=(a<<5)-a+chr,a&=a;return a});String.prototype.strip||(String.prototype.strip=function(){return this.replace(/(\r\n|\n|\r)/gm,"")});String.prototype.toTitleCase||(String.prototype.toTitleCase=function(){return this.replace(/\w\S*/g,function(a){return a.charAt(0).toUpperCase()+a.substr(1).toLowerCase()})});
String.prototype.entityify||(String.prototype.entityify=function(){return this.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")});
String.prototype.quote||(String.prototype.quote=function(){var a,b,c=this.length,d='"';for(b=0;b<c;b+=1)if(a=this.charAt(b)," "<=a){if("\\"===a||'"'===a)d+="\\";d+=a}else switch(a){case "\u0008":d+="\\b";break;case "\u000c":d+="\\f";break;case "\n":d+="\\n";break;case "\r":d+="\\r";break;case "\t":d+="\\t";break;default:a=a.charCodeAt(),d+="\\u00"+Math.floor(a/16).toString(16)+(a%16).toString(16)}return d+'"'});
String.prototype.supplant||(String.prototype.supplant=function(a){return this.replace(/{([^{}]*)}/g,function(b,c){var d=a[c];return"string"===typeof d||"number"===typeof d?d:b})});String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s*(\S*(?:\s+\S+)*)\s*$/,"$1")});String.prototype.pad||(String.prototype.pad=function(a,b){var b=b?b:"0",c=this;if(c.length<a)for(;c.length<a;)c=b+c;return c});window.mouseWheelTimeout=mouseWheelTimeout;var enableContext=!1,defaultMouse;
function MouseEventHandler(a,b,c,d){this.fallback=Function("return false;");this.down=b;this.click=a;this.move=c;this.wheel=d;this.down||(this.down=this.fallback);this.click||(this.click=this.fallback);this.move||(this.move=this.fallback);this.wheel||(this.wheel=this.fallback)}
function Mouse(a,b){this.element=a;this.handler=b;this.isdown=this.disabled=!1;this.button=null;this.dragged=!1;this.lastY=this.lastX=this.absoluteY=this.absoluteX=this.x=this.x=0;this.slider=null;this.spin=0;this.moveUpdate=this.wheelTimer=!1;a.addEventListener&&a.addEventListener("DOMMouseScroll",handleMouseWheel,!1);a.onmousedown=handleMouseDown;a.onmousewheel=handleMouseWheel;a.oncontextmenu=function(){return enableContext?(enableContext=!1,!0):!1}}
Mouse.prototype.update=function(a){a||(a=window.event);a.pageX||a.pageY?(this.x=a.pageX,this.y=a.pageY):(this.x=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,this.y=a.clientY+document.body.scrollTop+document.documentElement.scrollTop);this.absoluteX=this.x;this.absoluteY=this.y;var b=findElementPos(this.element);this.x-=b[0];this.y-=b[1];this.clientx=a.clientX-b[0];this.clienty=a.clientY-b[1]};
function findElementPos(a){var b=curtop=0;do b+=a.offsetLeft,curtop+=a.offsetTop;while(a=a.offsetParent);return[b,curtop]}function getMouse(a){var b=a.target.mouse;if(b)return b;for(a=a.target;a!=document;)if(a=a.parentNode,a.mouse)return a.mouse;return null}
function handleMouseDown(a){var b=getMouse(a);if(!b||b.disabled)return!0;var c=a||window.event;b.elementId=c.target.id;b.elementClass=c.target.className;b.dragged=!1;b.update(a);b.isdown||(b.lastX=b.absoluteX,b.lastY=b.absoluteY);b.isdown=!0;b.button=a.button;document.mouse=b;document.onmouseup=handleMouseUp;document.onmousemove=handleMouseMove;b=b.handler.down(a,b);!b&&a.preventDefault&&a.preventDefault();a.returnValue=b}
function handleMouseUp(a){var b=document.mouse;if(!b||b.disabled)return!0;var c=!0;b.isdown&&(b.update(a),c=b.handler.click(a,b),b.isdown=!1,b.button=null,b.dragged=!1);document.mouse=defaultMouse;!c&&a.preventDefault&&a.preventDefault();a.returnValue=c}
function handleMouseMove(a){var b=document.mouse;if(!b||b.disabled)return!0;b.update(a);b.deltaX=b.absoluteX-b.lastX;b.deltaY=b.absoluteY-b.lastY;var c=b.handler.move(a,b);!b.dragged&&b.isdown&&3<Math.abs(b.deltaX)+Math.abs(b.deltaY)&&(b.dragged=!0);b.moveUpdate&&(b.lastX=b.absoluteX,b.lastY=b.absoluteY);!c&&a.preventDefault&&a.preventDefault();a.returnValue=c}
function handleMouseWheel(a){var b=getMouse(a);if(!b||b.disabled)return!0;b.update(a);var c=0,d=!1;a||(a=window.event);a.wheelDelta?c=a.wheelDelta:a.detail&&(c=-a.detail);a.spin=0<c?1:-1;b.wheelTimer&&0==b.spin&&(document.mouse.event=a,setTimeout("mouseWheelTimeout(document.mouse);",50));b.spin+=a.spin;!b.wheelTimer&&0!=b.spin&&(d=b.handler.wheel(a,b));!d&&a.preventDefault&&a.preventDefault();a.returnValue=d}
function mouseWheelTimeout(a){a.event.spin=a.spin;a.spin=0;0!=a.event.spin&&a.handler.wheel(a.event,a)}
function ajaxReadFile(a,b,c,d){var e=new XMLHttpRequest,f=0;void 0!=d&&("number"==typeof d?f=d:e.onprogress=d);e.onreadystatechange=function(){if(0<f&&2<e.readyState){var c=parseInt(e.responseText.length);d&&setProgress(100*(c/f))}4==e.readyState&&(200==e.status?(d&&setProgress(100),debug("RECEIVED: "+a),b&&b(e.responseText,a)):b?b("Error: "+e.status):print("Ajax Read File Error: returned status code "+e.status+" "+e.statusText))};c?e.open("GET",a+"?d="+(new Date).getTime(),!0):e.open("GET",a,!0);
e.send(null)}function readURL(a,b,c){var d=new XMLHttpRequest,e=0;void 0!=c&&("number"==typeof c?e=c:d.onprogress=c);d.onreadystatechange=function(){if(0<e&&2<d.readyState){var a=parseInt(d.responseText.length);c&&setProgress(100*(a/e))}};b?d.open("GET",a+"?d="+(new Date).getTime(),!1):d.open("GET",a,!1);d.overrideMimeType("text/plain; charset=x-user-defined");d.send(null);if(200!=d.status)return"";c&&setProgress(100);return d.responseText}
function updateProgress(a){a.lengthComputable&&(setProgress(100*(a.loaded/a.total)),debug(a.loaded+" / "+a.total))}function setProgress(a){a=Math.round(a);$S("progressbar").width=3*a+"px";$("progressstatus").innerHTML=a+"%"}
function ajaxPost(a,b,c,d,e){var f=new XMLHttpRequest;void 0!=d&&(f.upload.onprogress=d);f.onreadystatechange=function(){4==f.readyState&&(200==f.status?(d&&setProgress(100),debug("POST: "+a),c&&c(f.responseText)):c?c("Error, status:"+f.status):print("Ajax Post Error: returned status code "+f.status+" "+f.statusText))};f.open("POST",a,!0);"string"==typeof b&&(f.setRequestHeader("Content-type","application/x-www-form-urlencoded"),f.setRequestHeader("Content-length",b.length));if(e)for(key in e)f.setRequestHeader(key,
e[key]);f.send(b)}
(function(){var a,b,c;function d(){Array.forEach(document.querySelectorAll("input[type=range]"),g);document.addEventListener("DOMNodeInserted",e,!0)}function e(a){f(a.target);a.target.querySelectorAll&&Array.forEach(a.target.querySelectorAll("input"),f)}function f(a,b){"input"!=a.localName||"range"==a.type||("range"==a.getAttribute("type")?g(a):b||setTimeout(f,0,a,!0))}function g(c){function d(b){var c=(parseFloat(getComputedStyle(this,0).width)-a)/m;c&&(r+=(b.clientX-t)/c,t=b.clientX,p=!0,this.value=
r)}function e(){this.removeEventListener("mousemove",d,!0);this.removeEventListener("mouseup",e,!0)}function f(a){return!isNaN(a)&&+a==parseFloat(a)}function g(){k=f(c.min)?+c.min:0;o=f(c.max)?+c.max:100;o<k&&(o=100<k?k:100);n=f(c.step)&&0<c.step?+c.step:1;m=o-k;l(!0)}function l(a){!u&&!v&&(j=c.getAttribute("value"));f(j)||(j=(k+o)/2);j=Math.round((j-k)/n)*n+k;j<k?j=k:j>o&&(j=k+~~(m/n)*n);p&&j!=w&&c.dispatchEvent(x);p=!1;if(a||j!=w)w=j,h(c,{background:"-moz-element(#__sliderthumb__) "+(m?100*((j-
k)/m):0)+"% no-repeat, "+A})}var u,v,p,w,r,t,k,o,n,m,j=c.value;s||(s=document.body.appendChild(document.createElement("hr")),h(s,{"-moz-appearance":q?"scale-horizontal":"scalethumb-horizontal",display:"block",visibility:"visible",opacity:1,position:"fixed",top:"-999999px"}),document.mozSetImageElement("__sliderthumb__",s));var y=function(){return""+j};c.__defineGetter__("value",y);c.__defineSetter__("value",function z(a){j=""+a;u=!0;l();delete c.value;c.value=j;c.__defineGetter__("value",y);c.__defineSetter__("value",
z)});c.__defineGetter__("type",function(){return"range"});["min","max","step"].forEach(function(a){c.hasAttribute(a)&&(v=!0);c.__defineGetter__(a,function(){return this.hasAttribute(a)?this.getAttribute(a):""});c.__defineSetter__(a,function(b){null===b?this.removeAttribute(a):this.setAttribute(a,b)})});c.readOnly=!0;h(c,B);g();c.addEventListener("DOMAttrModified",function(a){"value"==a.attrName&&!u?(j=a.newValue,l()):~["min","max","step"].indexOf(a.attrName)&&(g(),v=!0)},!0);c.addEventListener("mousedown",
function(c){setTimeout(function(){},0);if(!c.button&&m){var f=(parseFloat(getComputedStyle(this,0).width)-a)/m;if(f){var g=c.clientX-this.getBoundingClientRect().left-a/2-(j-k)*f;Math.abs(g)>b&&(p=!0,this.value-=-g/f);r=j;t=c.clientX;this.addEventListener("mousemove",d,!0);this.addEventListener("mouseup",e,!0)}}},!0);c.addEventListener("keydown",function(a){36<a.keyCode&&41>a.keyCode&&(onFocus.call(this),p=!0,this.value=j+(38==a.keyCode||39==a.keyCode?n:-n))},!0);c.addEventListener("blur",function(){this.style.boxShadow=
""},!0)}function h(a,b){for(var c in b)a.style.setProperty(c,b[c],"important")}c=document.createElement("input");try{if(c.type="range","range"==c.type)return}catch(l){return}if(document.mozSetImageElement&&"MozAppearance"in c.style){var s,q="MacIntel"==navigator.platform;b=q?9:6;a=q?22:12;c=q?16:20;var A="-moz-linear-gradient(top, transparent "+(q?"6px, #999 6px, #999 7px, #ccc 9px, #bbb 11px, #bbb 12px, transparent 12px":"9px, #999 9px, #bbb 10px, #fff 11px, transparent 11px")+", transparent)",B=
{"min-width":a+"px","min-height":c+"px","max-height":c+"px",padding:0,border:0,"border-radius":0,cursor:"default","text-indent":"-999999px"},x=document.createEvent("HTMLEvents");x.initEvent("change",!0,!1);"loading"==document.readyState?document.addEventListener("DOMContentLoaded",d,!0):d()}})();function Viewport(a,b,c,d){this.x=a;this.y=b;this.width=c;this.height=d}
function WebGL(a){this.program=null;this.modelView=new ViewMatrix;this.perspective=new ViewMatrix;this.textures=[];this.timer=null;if(!window.WebGLRenderingContext)throw"No browser WebGL support";var b={antialias:!0,premultipliedAlpha:!1};try{this.gl=a.getContext("webgl",b)||a.getContext("experimental-webgl",b)}catch(c){throw print("detectGL exception: "+c),"No context";}this.viewport=new Viewport(0,0,a.width,a.height);if(!this.gl)throw"Failed to get context";}
WebGL.prototype.setMatrices=function(){this.gl.uniformMatrix4fv(this.program.mvMatrixUniform,!1,this.modelView.matrix);this.gl.uniformMatrix4fv(this.program.pMatrixUniform,!1,this.perspective.matrix);if(this.program.nMatrixUniform){var a=mat4.create(this.modelView.matrix);mat4.inverse(a);mat4.transpose(a);this.gl.uniformMatrix4fv(this.program.nMatrixUniform,!1,a)}};
WebGL.prototype.draw2d=function(a){void 0==a&&(a=1);this.timer&&(clearTimeout(this.timer),this.timer=null);this.gl.viewport(this.viewport.x,this.viewport.y,this.viewport.width,this.viewport.height);this.gl.clear(this.gl.COLOR_BUFFER_BIT|this.gl.DEPTH_BUFFER_BIT);this.gl.enableVertexAttribArray(this.program.attributes.aVertexPosition);this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.vertexPositionBuffer);this.gl.vertexAttribPointer(this.program.attributes.aVertexPosition,this.vertexPositionBuffer.itemSize,
this.gl.FLOAT,!1,0,0);this.program.attributes.aTextureCoord&&(this.gl.enableVertexAttribArray(this.program.attributes.aTextureCoord),this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.textureCoordBuffer),this.gl.vertexAttribPointer(this.program.attributes.aTextureCoord,this.textureCoordBuffer.itemSize,this.gl.FLOAT,!1,0,0));this.setMatrices();1<a?(this.gl.enable(this.gl.BLEND),this.gl.blendFunc(this.gl.CONSTANT_ALPHA,this.gl.ONE_MINUS_CONSTANT_ALPHA),this.k=this.j=this.blendinc=0,this.antialias=a,this.pass()):
(this.gl.blendFunc(this.gl.SRC_ALPHA,this.gl.ONE_MINUS_SRC_ALPHA),this.gl.drawArrays(this.gl.TRIANGLE_STRIP,0,this.vertexPositionBuffer.numItems))};
WebGL.prototype.pass=function(){var a=1-this.blendinc,a=Math.pow(a,1.5);this.gl.blendColor(0,0,0,a);this.blendinc+=1/(this.antialias*this.antialias);this.gl.uniform2f(this.program.uniforms.offset,this.j/this.antialias-0.5,this.k/this.antialias-0.5);this.gl.drawArrays(this.gl.TRIANGLE_STRIP,0,this.vertexPositionBuffer.numItems);this.k++;this.k>=this.antialias&&(this.k=0,this.j++);if(this.j<this.antialias)if(this.time){var b=this;this.timer=setTimeout(function(){b.pass()},10)}else this.pass();else this.timer=
null};WebGL.prototype.updateTexture=function(a,b,c){void 0==c&&(c=this.gl.TEXTURE0);this.gl.activeTexture(c);this.gl.bindTexture(this.gl.TEXTURE_2D,a);this.gl.texImage2D(this.gl.TEXTURE_2D,0,this.gl.RGBA,this.gl.RGBA,this.gl.UNSIGNED_BYTE,b);this.gl.bindTexture(this.gl.TEXTURE_2D,null)};
WebGL.prototype.initTextureFramebuffer=function(a,b,c){this.rttFramebuffer=this.gl.createFramebuffer();this.gl.bindFramebuffer(this.gl.FRAMEBUFFER,this.rttFramebuffer);this.rttFramebuffer.width=a;this.rttFramebuffer.height=b;this.rttTexture=this.gl.createTexture();this.gl.bindTexture(this.gl.TEXTURE_2D,this.rttTexture);this.gl.texParameteri(this.gl.TEXTURE_2D,this.gl.TEXTURE_MAG_FILTER,this.gl.LINEAR);this.gl.texParameteri(this.gl.TEXTURE_2D,this.gl.TEXTURE_MIN_FILTER,this.gl.LINEAR);this.gl.texParameteri(this.gl.TEXTURE_2D,
this.gl.TEXTURE_WRAP_S,this.gl.CLAMP_TO_EDGE);this.gl.texParameteri(this.gl.TEXTURE_2D,this.gl.TEXTURE_WRAP_T,this.gl.CLAMP_TO_EDGE);this.gl.texImage2D(this.gl.TEXTURE_2D,0,this.gl.RGBA,this.rttFramebuffer.width,this.rttFramebuffer.height,0,this.gl.RGBA,this.gl.UNSIGNED_BYTE,null);this.gl.framebufferTexture2D(this.gl.FRAMEBUFFER,this.gl.COLOR_ATTACHMENT0,this.gl.TEXTURE_2D,this.rttTexture,0);c&&(this.rttDepthbuffer=this.gl.createRenderbuffer(),this.gl.bindRenderbuffer(this.gl.RENDERBUFFER,this.rttDepthbuffer),
this.gl.renderbufferStorage(this.gl.RENDERBUFFER,this.gl.DEPTH_COMPONENT16,a,b),this.gl.framebufferRenderbuffer(this.gl.FRAMEBUFFER,this.gl.DEPTH_ATTACHMENT,this.gl.RENDERBUFFER,this.rttDepthbuffer),this.gl.bindRenderbuffer(this.gl.RENDERBUFFER,null));this.gl.bindTexture(this.gl.TEXTURE_2D,null);this.gl.bindFramebuffer(this.gl.FRAMEBUFFER,null);a=this.gl.checkFramebufferStatus(this.gl.FRAMEBUFFER);a!=this.gl.FRAMEBUFFER_COMPLETE&&alert("Framebuffer error: "+a)};
WebGL.prototype.init2dBuffers=function(a){void 0==a&&(a=this.gl.TEXTURE0);this.vertexPositionBuffer=this.gl.createBuffer();this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.vertexPositionBuffer);this.gl.bufferData(this.gl.ARRAY_BUFFER,new Float32Array([1,1,-1,1,1,-1,-1,-1]),this.gl.STATIC_DRAW);this.vertexPositionBuffer.itemSize=2;this.vertexPositionBuffer.numItems=4;this.gl.activeTexture(a);this.gradientTexture=this.gl.createTexture();this.gl.bindTexture(this.gl.TEXTURE_2D,this.gradientTexture);this.gl.texParameteri(this.gl.TEXTURE_2D,
this.gl.TEXTURE_MAG_FILTER,this.gl.NEAREST);this.gl.texParameteri(this.gl.TEXTURE_2D,this.gl.TEXTURE_MIN_FILTER,this.gl.NEAREST);this.textureCoordBuffer=this.gl.createBuffer();this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.textureCoordBuffer);this.gl.bufferData(this.gl.ARRAY_BUFFER,new Float32Array([1,1,0,1,1,0,0,0]),this.gl.STATIC_DRAW);this.textureCoordBuffer.itemSize=2;this.textureCoordBuffer.numItems=4};
WebGL.prototype.loadTexture=function(a,b){void 0==b&&(b=this.gl.NEAREST);this.texid=this.textures.length;this.textures.push(this.gl.createTexture());this.gl.bindTexture(this.gl.TEXTURE_2D,this.textures[this.texid]);this.gl.texImage2D(this.gl.TEXTURE_2D,0,this.gl.LUMINANCE,this.gl.LUMINANCE,this.gl.UNSIGNED_BYTE,a);this.gl.texParameteri(this.gl.TEXTURE_2D,this.gl.TEXTURE_MAG_FILTER,b);this.gl.texParameteri(this.gl.TEXTURE_2D,this.gl.TEXTURE_MIN_FILTER,b);this.gl.texParameteri(this.gl.TEXTURE_2D,this.gl.TEXTURE_WRAP_S,
this.gl.CLAMP_TO_EDGE);this.gl.texParameteri(this.gl.TEXTURE_2D,this.gl.TEXTURE_WRAP_T,this.gl.CLAMP_TO_EDGE);this.gl.bindTexture(this.gl.TEXTURE_2D,null);return this.textures[this.texid]};WebGL.prototype.setPerspective=function(a,b,c,d){this.perspective.matrix=mat4.perspective(a,b,c,d)};WebGL.prototype.use=function(a){this.program=a;this.program.program&&this.gl.useProgram(this.program.program)};
function WebGLProgram(a,b,c){this.program=null;0>b.indexOf("main")&&(b=getSourceFromElement(b));0>c.indexOf("main")&&(c=getSourceFromElement(c));this.gl=a;this.program&&this.gl.isProgram(this.program)&&(this.gl.isShader(this.vshader)&&(this.gl.detachShader(this.program,this.vshader),this.gl.deleteShader(this.vshader)),this.gl.isShader(this.fshader)&&(this.gl.detachShader(this.program,this.fshader),this.gl.deleteShader(this.fshader)),this.gl.deleteProgram(this.program));this.program=this.gl.createProgram();
this.vshader=this.compileShader(b,this.gl.VERTEX_SHADER);this.fshader=this.compileShader(c,this.gl.FRAGMENT_SHADER);this.gl.attachShader(this.program,this.vshader);this.gl.attachShader(this.program,this.fshader);this.gl.linkProgram(this.program);if(!this.gl.getProgramParameter(this.program,this.gl.LINK_STATUS))throw"Could not initialise shaders: "+this.gl.getProgramInfoLog(this.program);}
WebGLProgram.prototype.compileShader=function(a,b){var c=this.gl.createShader(b);this.gl.shaderSource(c,a);this.gl.compileShader(c);if(!this.gl.getShaderParameter(c,this.gl.COMPILE_STATUS))throw this.gl.getShaderInfoLog(c);return c};
WebGLProgram.prototype.setup=function(a,b){if(this.program){void 0==a&&(a=["aVertexPosition","aTextureCoord"]);this.attributes={};for(var c in a)this.attributes[a[c]]=this.gl.getAttribLocation(this.program,a[c]),this.gl.enableVertexAttribArray(this.attributes[a[c]]);this.uniforms={};for(c in b)this.uniforms[b[c]]=this.gl.getUniformLocation(this.program,b[c]);this.mvMatrixUniform=this.gl.getUniformLocation(this.program,"uMVMatrix");this.pMatrixUniform=this.gl.getUniformLocation(this.program,"uPMatrix");
this.nMatrixUniform=this.gl.getUniformLocation(this.program,"uNMatrix")}};function ViewMatrix(){this.matrix=mat4.create();mat4.identity(this.matrix);this.stack=[]}ViewMatrix.prototype.toString=function(){return JSON.stringify(this.matrix)};ViewMatrix.prototype.push=function(a){a?(this.stack.push(mat4.create(a)),this.matrix=mat4.create(a)):this.stack.push(mat4.create(this.matrix))};ViewMatrix.prototype.pop=function(){if(0==this.stack.length)throw"Matrix stack underflow";return this.matrix=this.stack.pop()};
ViewMatrix.prototype.mult=function(a){mat4.multiply(this.matrix,a)};ViewMatrix.prototype.identity=function(){mat4.identity(this.matrix)};ViewMatrix.prototype.scale=function(a){mat4.scale(this.matrix,a)};ViewMatrix.prototype.translate=function(a){mat4.translate(this.matrix,a)};ViewMatrix.prototype.rotate=function(a,b){mat4.rotate(this.matrix,a*Math.PI/180,b)};
function Palette(a){this.background=new Colour("rgba(0,0,0,0)");this.colours=[];this.slider=new Image;this.slider.src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAPCAYAAAA2yOUNAAAAj0lEQVQokWNIjHT8/+zZs//Pnj37/+TJk/9XLp/+f+bEwf9HDm79v2Prqv9aKrz/GUYVEaeoMDMQryJXayWIoi0bFmFV1NWS+z/E1/Q/AwMDA0NVcez/LRsWoSia2luOUAADVcWx/xfO6/1/5fLp/1N7y//HhlmhKoCBgoyA/w3Vyf8jgyyxK4CBUF8zDAUAAJRXY0G1eRgAAAAASUVORK5CYII=";if(a){for(var a=a.split("\n"),b,c=0;c<a.length;c++){var d=a[c].trim();if(d)if(d=d.split("="),
"Background"==d[0])this.background=new Colour(d[1]);else if("P"==d[0][0])b=parseFloat(d[1]);else if("C"==d[0][0]){if(this.colours.push(new ColourPos(d[1],b)),1==b)break}else d[0]&&this.colours.push(new ColourPos(d[1],d[0]))}b=!1;for(a=0;a<this.colours.length;a++)0<this.colours[a].colour.alpha&&(b=!0),1<this.colours[a].colour.alpha&&(this.colours[a].colour.alpha=1);if(!b)for(a=0;a<this.colours.length;a++)this.colours[a].colour.alpha=1}else this.colours.push(new ColourPos("rgba(255,255,255,1)",0)),
this.colours.push(new ColourPos("rgba(0,0,0,1)",1))}Palette.prototype.newColour=function(a,b){this.colours.push(new ColourPos(b,a));this.colours.sort(function(a,b){return a.position-b.position});for(var c=1;c<this.colours.length-1;c++)if(this.colours[c].position==a)return c;return-1};Palette.prototype.inRange=function(a,b,c){for(var d=0;d<this.colours.length;d++){var e=this.colours[d].position*c;if(a==e||1<b&&a>=e-b/2&&a<=e+b/2)return d}return-1};
Palette.prototype.inDragRange=function(a,b,c){for(var d=1;d<this.colours.length-1;d++){var e=this.colours[d].position*c;if(a==e||1<b&&a>=e-b/2&&a<=e+b/2)return d}return 0};Palette.prototype.remove=function(a){this.colours.splice(a,1)};Palette.prototype.toString=function(){for(var a="Background="+this.background.html(),b=0;b<this.colours.length;b++)a+="\n"+this.colours[b].position.toFixed(6)+"="+this.colours[b].colour.html();return a};
Palette.prototype.draw=function(a,b){if(!this.slider.width&&b){var c=this;setTimeout(function(){c.draw(a,b)},150)}else if(a){var d=/webkit/.test(navigator.userAgent.toLowerCase());0==this.colours.length&&(this.background=new Colour("#ffffff"),this.colours.push(new ColourPos("#000000",0)),this.colours.push(new ColourPos("#ffffff",1)));list=this.colours.slice(0);list.sort(function(a,b){return a.position-b.position});if(a.getContext){var e=a.width,f=a.height,g=a.getContext("2d");g.clearRect(0,0,e,f);
if(d)for(var h=0,d=1;d<list.length;d++){var l=Math.round(e*list[d].position);g.fillStyle=g.createLinearGradient(h,0,l,0);g.fillStyle.addColorStop(0,list[d-1].colour.html());g.fillStyle.addColorStop(1,list[d].colour.html());g.fillRect(h,0,l-h,f);h=l}else{g.fillStyle=g.createLinearGradient(0,0,e,0);for(d=0;d<list.length;d++)g.fillStyle.addColorStop(list[d].position,list[d].colour.html());g.fillRect(0,0,e,f)}if(d=document.getElementById("backgroundCUR"))d.style.background=this.background.html();if(b)for(d=
1;d<list.length-1;d++)f=Math.floor(e*list[d].position)+0.5,h=list[d].colour.HSV(),g.strokeStyle=50<h.V?"black":"white",g.beginPath(),g.moveTo(f,0),g.lineTo(f,a.height),g.closePath(),g.stroke(),f-=this.slider.width/2,g.drawImage(this.slider,f,0)}else alert("getContext failed!")}else alert("Invalid canvas!")};function ColourPos(a,b){this.position=parseFloat(b);this.colour=a?"object"==typeof a?a:new Colour(a):new Colour("#000000")}
function Colour(a){"undefined"==typeof a?this.set("#ffffff"):"string"==typeof a?this.set(a):"object"==typeof a?"undefined"!=typeof a.H?this.setHSV(a):"undefined"!=typeof a.red?(this.red=a.red,this.green=a.green,this.blue=a.blue,this.alpha=a.alpha):a.R?(this.red=a.R,this.green=a.G,this.blue=a.B,this.alpha="undefined"==typeof a.A?1:a.A):(this.red=a[0],this.green=a[1],this.blue=a[2],this.alpha="undefined"==typeof a[3]?1:a[3]):this.fromInt(a)}
Colour.prototype.set=function(a){a||(a="#ffffff");var b=/^rgba?\((\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,?\s*(\d\.?\d*)?\)$/.exec(a);b?(this.red=parseInt(b[1]),this.green=parseInt(b[2]),this.blue=parseInt(b[3]),this.alpha="undefined"==typeof b[4]?1:parseFloat(b[4])):"#"==a.charAt(0)?(a=a.substring(1,7),this.alpha=1,this.red=parseInt(a.substring(0,2),16),this.green=parseInt(a.substring(2,4),16),this.blue=parseInt(a.substring(4,6),16)):this.fromInt(parseInt(a))};
Colour.prototype.fromInt=function(a){this.red=a&255;this.green=(a&65280)>>>8;this.blue=(a&16711680)>>>16;this.alpha=((a&4278190080)>>>24)/255};Colour.prototype.toInt=function(){var a=this.red,a=a+(this.green<<8),a=a+(this.blue<<16);return a+=Math.round(255*this.alpha)<<24};Colour.prototype.toString=function(){return this.html()};Colour.prototype.html=function(){return"rgba("+this.red+","+this.green+","+this.blue+","+this.alpha+")"};
Colour.prototype.rgbaGL=function(){return new Float32Array([this.red/255,this.green/255,this.blue/255,this.alpha])};Colour.prototype.rgbaGLSL=function(){var a=this.rgbaGL();return"rgba("+a[0].toFixed(4)+","+a[1].toFixed(4)+","+a[2].toFixed(4)+","+a[3].toFixed(4)+")"};Colour.prototype.rgba=function(){return[this.red,this.green,this.blue,this.alpha]};Colour.prototype.rgbaObj=function(){return{R:this.red,G:this.green,B:this.blue,A:this.alpha}};Colour.prototype.print=function(){print(this.printString(!0))};
Colour.prototype.printString=function(a){return"R:"+this.red+" G:"+this.green+" B:"+this.blue+(a?" A:"+this.alpha:"")};Colour.prototype.htmlHex=function(){HEX=function(a){a=Math.round(Math.min(Math.max(0,a),255));return"0123456789ABCDEF".charAt((a-a%16)/16)+"0123456789ABCDEF".charAt(a%16)};return"#"+HEX(this.red)+HEX(this.green)+HEX(this.blue)};
Colour.prototype.hex=function(){HEX=function(a){a=Math.round(Math.min(Math.max(0,a),255));return"0123456789ABCDEF".charAt((a-a%16)/16)+"0123456789ABCDEF".charAt(a%16)};return HEX(this.red)+HEX(this.green)+HEX(this.blue)+HEX(255*this.alpha)};
Colour.prototype.setHSV=function(a){var b,c,d,e,f;f=a.S/100;var g=a.V/100,h=a.H/360;if(0<f){1<=h&&(h=0);h*=6;F=h-Math.floor(h);d=Math.round(255*g*(1-f));e=Math.round(255*g*(1-f*F));f=Math.round(255*g*(1-f*(1-F)));g=Math.round(255*g);switch(Math.floor(h)){case 0:b=g;c=f;e=d;break;case 1:b=e;c=g;e=d;break;case 2:b=d;c=g;e=f;break;case 3:b=d;c=e;e=g;break;case 4:b=f;c=d;e=g;break;case 5:b=g,c=d}this.red=b?b:0;this.green=c?c:0;this.blue=e?e:0}else this.blue=this.green=this.red=g=Math.round(255*g);this.alpha=
"undefined"==typeof a.A?1:a.A};Colour.prototype.HSV=function(){var a=this.red/255,b=this.green/255,c=this.blue/255,d=Math.min(a,b,c),e=Math.max(a,b,c);deltaMax=e-d;var f,g,h,l;0==deltaMax?d=f=0:(d=deltaMax/e,g=((e-a)/6+deltaMax/2)/deltaMax,h=((e-b)/6+deltaMax/2)/deltaMax,l=((e-c)/6+deltaMax/2)/deltaMax,a==e?f=l-h:b==e?f=1/3+g-l:c==e&&(f=2/3+h-g),0>f&&(f+=1),1<f&&(f-=1));return{H:360*f,S:100*d,V:100*e}};Colour.prototype.HSVA=function(){var a=this.HSV();a.A=this.alpha;return a};
Colour.prototype.interpolate=function(a,b){this.red=Math.round(this.red+b*(a.red-this.red));this.green=Math.round(this.green+b*(a.green-this.green));this.blue=Math.round(this.blue+b*(a.blue-this.blue));this.alpha=Math.round(this.alpha+b*(a.alpha-this.alpha))};Colour.prototype.blend=function(a){return new Colour([Math.round((1-a.alpha)*this.red+a.alpha*a.red),Math.round((1-a.alpha)*this.green+a.alpha*a.green),Math.round((1-a.alpha)*this.blue+a.alpha*a.blue),(1-a.alpha)*this.alpha+a.alpha*a.alpha])};
function scale(a,b,c,d){return clamp(d*a/b,c,d)}function clamp(a,b,c){return Math.max(b,Math.min(c,a))}
function ColourPicker(a,b){this.savefn=a;this.abortfn=b;this.size=170;this.sv=5;this.oh=2;this.picked={H:360,S:100,V:100,A:1};this.max={H:360,S:100,V:100,A:1};this.colour=new Colour;this.mouse=new Mouse($("picker"),this);this.mouse.moveUpdate=!0;$("picker").mouse=this.mouse;var c,d="",e;for(c=0;c<=this.size;c++)e=new Colour({H:Math.round(360/this.size*c),S:100,V:100,A:1}),d+="<div class='hue' style='background: "+e.htmlHex()+";'> </div>";$("Hmodel").innerHTML=d;d="";for(c=0;c<=this.size;c++)e=1-c/
this.size,d+="<div class='opacity' style='opacity: "+e.toFixed(2)+";'> </div>";$("Omodel").innerHTML=d}ColourPicker.prototype.pick=function(a,b,c){this.update(a.HSVA());"block"!=$S("picker").display&&this.pos(b,c)};
ColourPicker.prototype.pos=function(a,b){0>a&&(a=0);0>b&&(b=0);$S("picker").left=a+"px";$S("picker").top=b+"px";$S("picker").display="block";var c=$("picker").offsetWidth,d=$("picker").offsetHeight;a+c>window.innerWidth-20&&($S("picker").left=window.innerWidth-c-20+"px");b+d>window.innerHeight-20&&($S("picker").top=window.innerHeight-d-20+"px")};
ColourPicker.prototype.select=function(a,b,c){if(!b||!c)var d=findElementPos(a),b=b?b:d[0]+32,c=c?c:d[1]+32;this.update((new Colour(a.style.backgroundColor)).HSVA());"block"!=$S("picker").display&&(this.pos(b,c),this.element=a)};
ColourPicker.prototype.click=function(a,b){"pickCLOSE"==b.elementId?(this.abortfn&&this.abortfn(),toggle("picker")):"pickOK"==b.elementId?(this.savefn&&this.savefn(this.picked),this.element&&(this.element.style.backgroundColor=(new Colour(this.picked)).html()),toggle("picker")):"SV"==b.elementId?this.setSV(b):"Hslide"==b.elementId||"hue"==b.elementClass?this.setHue(b):("Oslide"==b.elementId||"opacity"==b.elementClass)&&this.setOpacity(b)};ColourPicker.prototype.down=function(){return!1};
ColourPicker.prototype.move=function(a,b){if(b.isdown&&!(0<b.button))if("picker"==b.elementId||"pickCUR"==b.elementId||"pickRGB"==b.elementId){var c=$S("picker");c.left=parseInt(c.left)+b.deltaX+"px";c.top=parseInt(c.top)+b.deltaY+"px"}else"SV"==b.elementId?this.setSV(b):"Hslide"==b.elementId||"hue"==b.elementClass?this.setHue(b):("Oslide"==b.elementId||"opacity"==b.elementClass)&&this.setOpacity(b)};ColourPicker.prototype.wheel=function(a){this.incHue(-a.spin)};
ColourPicker.prototype.setSV=function(a){var b=a.clientx-parseInt($("SV").offsetLeft),a=a.clienty-parseInt($("SV").offsetTop);this.picked.S=scale(b,this.size,0,this.max.S);this.picked.V=this.max.V-scale(a,this.size,0,this.max.V);this.update(this.picked)};ColourPicker.prototype.setHue=function(a){parseInt($("H").offsetLeft);a=a.clienty-parseInt($("H").offsetTop);this.picked.H=scale(a,this.size,0,this.max.H);this.update(this.picked)};
ColourPicker.prototype.incHue=function(a){this.picked.H+=a;this.picked.H=clamp(this.picked.H,0,this.max.H);this.update(this.picked)};ColourPicker.prototype.setOpacity=function(a){parseInt($("O").offsetLeft);a=a.clienty-parseInt($("O").offsetTop);this.picked.A=1-clamp(a/this.size,0,1);this.update(this.picked)};ColourPicker.prototype.updateString=function(a){a||(a=prompt("Edit colour:",this.colour.html()));a&&(this.colour=new Colour(a),this.update(this.colour.HSV()))};
ColourPicker.prototype.update=function(a){this.picked=a;this.colour=new Colour(a);rgba=this.colour.rgbaObj();rgbaStr=this.colour.html();bgcol=new Colour({H:a.H,S:100,V:100,A:255});$("pickRGB").innerHTML=this.colour.printString();$S("pickCUR").background=rgbaStr;$S("pickCUR").backgroundColour=rgbaStr;$S("SV").backgroundColor=bgcol.htmlHex();$S("Hslide").top=this.size*(a.H/360)-this.oh+"px";$S("SVslide").top=Math.round(this.size-this.size*(a.V/100)-this.sv)+"px";$S("SVslide").left=Math.round(this.size*
(a.S/100)-this.sv)+"px";$S("Oslide").top=this.size*(1-a.A)-this.oh-1+"px"};function GradientEditor(a,b){this.canvas=a;this.callback=b;this.changed=!0;this.inserting=!1;this.element=this.editing=null;this.spin=0;this.picker=new ColourPicker(this.save.bind(this),this.cancel.bind(this));this.palette=new Palette;this.canvas.mouse=new Mouse(this.canvas,this);this.canvas.oncontextmenu="return false;";this.canvas.oncontextmenu=function(){return!1}}
GradientEditor.prototype.read=function(a){this.palette=new Palette(a);this.reset();this.update(!0)};GradientEditor.prototype.update=function(a){this.changed=!0;this.palette.draw(this.canvas,!0);!a&&this.callback&&this.callback(this)};GradientEditor.prototype.get=function(a){if(!this.changed)return!1;this.changed=!1;this.palette.draw(a,!1);return!0};
GradientEditor.prototype.insert=function(a,b,c){this.inserting=!0;var d=new Colour;this.editing=this.palette.newColour(a,d);this.update();this.picker.pick(d,b,c)};GradientEditor.prototype.editBackground=function(a){this.editing=-1;var b=findElementPos(a);this.element=a;this.picker.pick(this.palette.background,b[0]+32,b[1]+32)};
GradientEditor.prototype.edit=function(a,b,c){"number"==typeof a?(this.editing=a,this.picker.pick(this.palette.colours[a].colour,b,c)):"object"==typeof a&&(this.cancel(),this.element=a,b=new Colour(a.style.backgroundColor),a=findElementPos(a),this.picker.pick(b,a[0]+32,a[1]+32));this.update()};
GradientEditor.prototype.save=function(a){null!=this.editing&&(0<=this.editing?this.palette.colours[this.editing].colour.setHSV(a):this.palette.background.setHSV(a));if(this.element){var b=new Colour(0);b.setHSV(a);this.element.style.backgroundColor=b.html()}this.reset();this.update()};GradientEditor.prototype.cancel=function(){0<=this.editing&&this.inserting&&this.palette.remove(this.editing);this.reset();this.update()};
GradientEditor.prototype.reset=function(){this.inserting=!1;this.element=this.editing=null};
GradientEditor.prototype.click=function(a,b){if(a.ctrlKey){for(var c=0;c<this.palette.colours.length;c++)this.palette.colours[c].position=1-this.palette.colours[c].position;this.update();return!1}b.x=b.clientx;b.x=b.clientx;if(null!=b.slider)return b.slider=null,this.update(),!1;var d=this.canvas;if(d.getContext){this.cancel();d.getContext("2d");var e=findElementPos(d)[1]+30,c=this.palette.inRange(b.x,this.palette.slider.width,d.width);0<=c?0==a.button?this.edit(c,a.clientX-128,e):2==a.button&&(this.palette.remove(c),
this.update()):this.insert(b.x/d.width,a.clientX-128,e)}return!1};GradientEditor.prototype.down=function(){return!1};GradientEditor.prototype.move=function(a,b){if(!b.isdown)return!0;b.x=b.clientx;b.x=b.clientx;if(null==b.slider){var c=this.palette.inDragRange(b.x,this.palette.slider.width,this.canvas.width);0<c&&(b.slider=c)}null==b.slider?b.isdown=!1:(1>b.x&&(b.x=1),b.x>this.canvas.width-1&&(b.x=this.canvas.width-1),this.palette.colours[b.slider].position=b.x/this.canvas.width,this.update(!0))};
GradientEditor.prototype.wheel=function(a){this.timer?clearTimeout(this.timer):this.canvas.style.cursor="wait";this.spin+=0.01*a.spin;var b=this;this.timer=setTimeout(function(){b.cycle(b.spin);b.spin=0},150)};GradientEditor.prototype.leave=function(){};
GradientEditor.prototype.cycle=function(a){this.canvas.style.cursor="default";this.timer=null;for(var b=1;b<this.palette.colours.length-1;b++){var c=this.palette.colours[b].position,c=c+a;0>=c&&(c+=1);1<=c&&(c-=1);this.palette.colours[b].position=c}this.update()};
