ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mat-block.c mat-block-ops.c
SOURCEF  =
SOURCEH  =
OBJSC    = mat-block.o mat-block-ops.o
OBJSF    =
LIBBASE  = libpetscext_mat
MANSEC   = Mat
LOCDIR   = src/mat/impls/block/

include ${PETSCEXT2_DIR}/conf/petscext_common
